"""empty message

Revision ID: 09b412f080c6
Revises: 3abde18709bf
Create Date: 2021-07-28 17:49:27.668206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b412f080c6'
down_revision = '3abde18709bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quickscenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quickscene_sounds',
    sa.Column('sounds_id', sa.Integer(), nullable=True),
    sa.Column('quickscenes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quickscenes_id'], ['quickscenes.id'], ),
    sa.ForeignKeyConstraint(['sounds_id'], ['sounds.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quickscene_sounds')
    op.drop_table('quickscenes')
    # ### end Alembic commands ###
