"""empty message

Revision ID: 2bc9f00f9b22
Revises: 314a42cfe926
Create Date: 2021-07-02 16:32:37.934584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc9f00f9b22'
down_revision = '314a42cfe926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joined_snds_cats',
    sa.Column('sounds_id', sa.Integer(), nullable=True),
    sa.Column('categories_id', sa.Integer(), nullable=True),
    sa.Column('blahblah_blah', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sounds_id'], ['sounds.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joined_snds_cats')
    # ### end Alembic commands ###
