"""empty message

Revision ID: d34ceea4c2c3
Revises: 64c2955998bc
Create Date: 2021-07-01 08:02:26.298188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34ceea4c2c3'
down_revision = '64c2955998bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sounds', sa.Column('arrangement', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sounds', 'arrangement')
    # ### end Alembic commands ###
