"""empty message

Revision ID: a455f3460138
Revises: 2bc9f00f9b22
Create Date: 2021-07-02 16:33:49.657405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a455f3460138'
down_revision = '2bc9f00f9b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joined_snds_cats',
    sa.Column('sounds_id', sa.Integer(), nullable=True),
    sa.Column('categories_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sounds_id'], ['sounds.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joined_snds_cats')
    # ### end Alembic commands ###
